# Generated by Django 4.0.5 on 2022-06-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cart_instamojo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='instamojo_id',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
